// docs/security/authorization.md holds one table of every route with the permission it needs. The
// table is generated from the LIVE route registry, and this test fails when the document differs
// from it, so the matrix cannot drift from the code (ASVS 8.1.1). To regenerate after a route
// change: `UPDATE_AUTHZ_DOC=1 pnpm exec vitest run --project @scorpion/server apps/server/src/authorization-doc.test.ts`
// (Docker needed), then `pnpm exec prettier --write docs/security/authorization.md`.
import { readFileSync, writeFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { useIdentityApp } from './testing/identity-app.ts';

const app = useIdentityApp();
const DOC = new URL('../../../docs/security/authorization.md', import.meta.url);
const START = '<!-- routes:start (generated by authorization-doc.test.ts, do not edit) -->';
const END = '<!-- routes:end -->';

const audited = (audit: unknown) =>
  audit === true ? 'yes' : audit && typeof audit === 'object' ? 'yes, with body' : 'no';

describe('docs/security/authorization.md', () => {
  it('lists every route of the live registry with its permission [ASVS-8.1.1]', async () => {
    const { kernel } = await app.start();
    const rows = kernel.routes
      .map(({ module, surface, route }) => ({
        key: `${route.method.toUpperCase()} ${route.path}`,
        module,
        surface,
        access: route.public ? '**public**' : `\`${route.permission}\``,
        limit: route.rateLimit ?? 'default',
        audit: audited(route.audit),
      }))
      .sort((a, b) => a.module.localeCompare(b.module) || a.key.localeCompare(b.key));
    const table = [
      '| Route | Module | Permission | Rate limit | Audited |',
      '| --- | --- | --- | --- | --- |',
      ...rows.map(
        (row) =>
          `| \`${row.key}\` | ${row.module} | ${row.access} | ${row.limit} | ${row.audit} |`,
      ),
    ].join('\n');

    const text = readFileSync(DOC, 'utf8');
    const from = text.indexOf(START);
    const to = text.indexOf(END);
    expect(from, 'the start marker is missing in authorization.md').toBeGreaterThanOrEqual(0);
    expect(to, 'the end marker is missing in authorization.md').toBeGreaterThan(from);
    const current = text.slice(from + START.length, to).trim();
    // Prettier pads table cells: compare without the padding.
    const squash = (value: string) => value.replaceAll(/[ \t]+/g, ' ').replaceAll(/-{3,}/g, '---');
    if (process.env.UPDATE_AUTHZ_DOC === '1') {
      writeFileSync(DOC, `${text.slice(0, from + START.length)}\n\n${table}\n\n${text.slice(to)}`);
      return;
    }
    expect(
      squash(current).replaceAll(/\| /g, '|').replaceAll(/ \|/g, '|'),
      'the route table of docs/security/authorization.md differs from the live registry: regenerate it (see the header of authorization-doc.test.ts)',
    ).toBe(squash(table).replaceAll(/\| /g, '|').replaceAll(/ \|/g, '|'));
  });
});
