// `pnpm openapi:generate [--check]`: writes the OpenAPI documents of the routes the generated profile
// registers, and the types the web app's API client is checked against (ADR-0027).
//
//   apps/web/src/generated/openapi-v1.json              the public API (v1) of the profile, for /docs
//   packages/contracts/src/generated/schema.ts          the types of the internal API (openapi-typescript), only for `full`
//
// The client is typed against the `full` profile, the superset; the Docker build of another profile
// writes only the v1 document. No database is needed: each module's `routes()` runs with a registrar
// that only collects the route definitions and with stand-ins for the services, which never run.
// `--check` reports a file that differs instead of writing it (`pnpm check` runs it); `--web-only` writes the v1 document alone.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { generateOpenApiDocument, type AppRoute } from '@scorpion/contracts';
import type { ModuleManifest } from '@scorpion/kernel';
import { profileName, sources } from './generated/profile.ts';

const root = resolve(import.meta.dirname, '../../..');
const check = process.argv.includes('--check');
// The Docker build of a profile writes the web app's v1 document only: the client types belong to the
// committed `full` profile and need a development dependency that an image does not install.
const webOnly = process.argv.includes('--web-only');

/** Something that can be called, indexed and awaited without doing anything: a service that never runs. */
function standIn(): unknown {
  const target = function () {};
  return new Proxy(target, {
    get: (_, property) => (property === 'then' ? undefined : standIn()),
    apply: () => standIn(),
  });
}

function collectRoutes(manifests: readonly ModuleManifest[]) {
  const internal: AppRoute[] = [];
  const v1: AppRoute[] = [];
  for (const manifest of manifests) {
    manifest.routes?.(
      {
        internal: (route) => internal.push(route),
        public: (_version, route) => v1.push(route),
        service: () => standIn() as never,
      },
      standIn() as never,
    );
  }
  return { internal, v1 };
}

const { internal, v1 } = collectRoutes(sources.map((source) => source.manifest));

const outputs = new Map<string, string>();
const json = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`;

outputs.set(
  'apps/web/src/generated/openapi-v1.json',
  json(
    generateOpenApiDocument(v1, {
      title: 'Public API',
      version: '1',
      description: 'The public API, version 1.',
    }),
  ),
);

if (profileName === 'full' && !webOnly) {
  const { default: openapiTS, astToString } = await import('openapi-typescript');
  const document = generateOpenApiDocument(internal, {
    title: 'Internal API',
    version: '1',
    description: 'The API of the web application. Not for third parties.',
  });
  const ast = await openapiTS(document as never);
  outputs.set(
    'packages/contracts/src/generated/schema.ts',
    `// GENERATED by \`pnpm openapi:generate\` from the routes of profile "full". Do not edit.\n${astToString(ast)}`,
  );
}

let stale = false;
for (const [file, content] of outputs) {
  const path = resolve(root, file);
  // Read and compare, never test-then-read: a missing file is simply "different".
  let current: string | undefined;
  try {
    current = readFileSync(path, 'utf8');
  } catch {
    current = undefined;
  }
  if (current === content) continue;
  if (check) {
    console.error(`${file} is out of date. Run: pnpm openapi:generate`);
    stale = true;
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
    console.log(`wrote ${file}`);
  }
}
process.exit(stale ? 1 : 0);
