// `pnpm modules:sync [--check]`: writes packages/kernel/src/workspace-modules.ts, the list of
// module ids that `defineProfile()` checks against. `--check` fails if the file is out of date.
import { readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { scanModulePackages } from '@scorpion/kernel';

const root = resolve(import.meta.dirname, '..');
const target = join(root, 'packages/kernel/src/workspace-modules.ts');

const entries: [string, string][] = [];
for (const pkg of scanModulePackages([join(root, 'modules')])) {
  const { default: manifest } = (await import(
    pathToFileURL(join(root, pkg.dir, 'module.ts')).href
  )) as {
    default: { id: string };
  };
  entries.push([manifest.id, pkg.name]);
}
entries.sort(([a], [b]) => a.localeCompare(b));

const body = entries.length
  ? `{\n${entries.map(([id, name]) => `  '${id}': '${name}',`).join('\n')}\n}`
  : '{}';
const content = `// GENERATED by \`pnpm modules:sync\` from the packages in modules/. Do not edit by hand.
// Maps each module id to its package name; \`ModuleId\` is what defineProfile() checks against.
export const WORKSPACE_MODULES = ${body} as const satisfies Record<string, string>;

export type ModuleId = keyof typeof WORKSPACE_MODULES;
`;

if (process.argv.includes('--check')) {
  if (readFileSync(target, 'utf8') !== content) {
    console.error(
      'packages/kernel/src/workspace-modules.ts is out of date. Run: pnpm modules:sync',
    );
    process.exit(1);
  }
} else {
  writeFileSync(target, content);
}
