export interface ProfileModuleInput {
  profileName: string;
  /** Module ids, in profile order. */
  moduleIds: readonly string[];
  /** The package names for `moduleIds`, in the same order. */
  packageNames: readonly string[];
}

/**
 * The source of `apps/server/src/generated/profile.ts`: static imports of each module's manifest
 * and package.json. Static imports let the bundler and the image build see exactly which modules
 * the server contains (ADR 0002).
 */
export function renderProfileModule({
  profileName,
  moduleIds,
  packageNames,
}: ProfileModuleInput): string {
  const imports = packageNames.flatMap((name, index) => [
    `import module${index} from '${name}/module';`,
    `import package${index} from '${name}/package.json' with { type: 'json' };`,
  ]);
  const sources = packageNames.map(
    (_, index) => `  { manifest: module${index}, packageJson: package${index} },`,
  );
  return [
    `// GENERATED by \`pnpm scorpion profile:generate ${profileName}\`. Do not edit; regenerate instead.`,
    '// The server imports modules only through this file (ADR 0002).',
    ...(imports.length > 0
      ? ["import type { ModuleSource } from '@scorpion/kernel';", ...imports]
      : []),
    '',
    `export const profileName = ${JSON.stringify(profileName)};`,
    '',
    `export const moduleIds = ${JSON.stringify(moduleIds)} as const;`,
    '',
    imports.length > 0
      ? `export const sources: ModuleSource[] = [\n${sources.join('\n')}\n];`
      : 'export const sources: never[] = [];',
    '',
  ].join('\n');
}
