import { describe, expect, it } from 'vitest';
import { renderProfileModule, renderUiModule } from './codegen.ts';

describe('renderProfileModule', () => {
  it('writes static imports of each manifest and package.json', () => {
    const source = renderProfileModule({
      profileName: 'kpi-tracker',
      moduleIds: ['kpi.framework', 'core.ui-shell'],
      packageNames: ['@scorpion/kpi-framework', '@scorpion/core-ui-shell'],
    });
    expect(source).toContain("import module0 from '@scorpion/kpi-framework/module';");
    expect(source).toContain(
      "import package0 from '@scorpion/kpi-framework/package.json' with { type: 'json' };",
    );
    expect(source).toContain("import module1 from '@scorpion/core-ui-shell/module';");
    expect(source).toContain('{ manifest: module1, packageJson: package1 },');
    expect(source).toContain('export const profileName = "kpi-tracker";');
    expect(source).toContain(
      'export const moduleIds = ["kpi.framework","core.ui-shell"] as const;',
    );
  });

  it('writes a valid file for a profile without modules', () => {
    const source = renderProfileModule({ profileName: 'full', moduleIds: [], packageNames: [] });
    expect(source).not.toContain('import ');
    expect(source).toContain('export const sources: never[] = [];');
  });
});

describe('renderUiModule', () => {
  it('imports the ui entry of each listed package and lists its pages and texts', () => {
    const source = renderUiModule({
      profileName: 'full',
      hasShell: true,
      uiPackages: ['@scorpion/core-ui-shell', '@scorpion/pages'],
    });
    expect(source).toContain("import * as ui0 from '@scorpion/core-ui-shell/ui';");
    expect(source).toContain("import * as ui1 from '@scorpion/pages/ui';");
    expect(source).toContain('export const hasShell = true;');
    expect(source).toContain(
      '{ package: "@scorpion/pages", routes: ui1.default, messages: ui1.messages },',
    );
    expect(source).toContain('GENERATED by `pnpm scorpion profile:generate full`');
  });

  it('is empty without the shell, even when modules have pages', () => {
    const source = renderUiModule({
      profileName: 'headless',
      hasShell: false,
      uiPackages: ['@scorpion/pages'],
    });
    expect(source).toContain('export const hasShell = false;');
    expect(source).toContain('export const uiModules: UiModule[] = [];');
    expect(source).not.toContain('import * as');
    expect(source).not.toContain('@scorpion/pages');
  });

  it('is the same text every time', () => {
    const input = { profileName: 'p', hasShell: true, uiPackages: ['@scorpion/a'] };
    expect(renderUiModule(input)).toBe(renderUiModule(input));
  });
});
