export interface ProfileModuleInput {
  profileName: string;
  /** Module ids, in profile order. */
  moduleIds: readonly string[];
  /** The package names for `moduleIds`, in the same order. */
  packageNames: readonly string[];
}

/**
 * The source of `apps/server/src/generated/profile.ts`: static imports of each module's manifest
 * and package.json. Static imports let the bundler and the image build see exactly which modules
 * the server contains (ADR 0002).
 */
export function renderProfileModule({
  profileName,
  moduleIds,
  packageNames,
}: ProfileModuleInput): string {
  const imports = packageNames.flatMap((name, index) => [
    `import module${index} from '${name}/module';`,
    `import package${index} from '${name}/package.json' with { type: 'json' };`,
  ]);
  const sources = packageNames.map(
    (_, index) => `  { manifest: module${index}, packageJson: package${index} },`,
  );
  return [
    `// GENERATED by \`pnpm scorpion profile:generate ${profileName}\`. Do not edit; regenerate instead.`,
    '// The server imports modules only through this file (ADR 0002).',
    ...(imports.length > 0
      ? ["import type { ModuleSource } from '@scorpion/kernel';", ...imports]
      : []),
    '',
    `export const profileName = ${JSON.stringify(profileName)};`,
    '',
    `export const moduleIds = ${JSON.stringify(moduleIds)} as const;`,
    '',
    imports.length > 0
      ? `export const sources: ModuleSource[] = [\n${sources.join('\n')}\n];`
      : 'export const sources: never[] = [];',
    '',
  ].join('\n');
}

export interface UiModuleInput {
  profileName: string;
  /** Whether the profile has `core.ui-shell`: without it there is no web app and the table is empty. */
  hasShell: boolean;
  /** Packages of the profile's modules that export `./ui`, in profile order. */
  uiPackages: readonly string[];
}

/**
 * The source of `apps/web/src/generated/ui.ts`: one static import of the `ui` entry of every module of
 * the profile that has one (ADR-0027). The entry is small (its pages are lazy imports inside it), so
 * the web app knows at build time exactly which pages the image can show.
 */
export function renderUiModule({ profileName, hasShell, uiPackages }: UiModuleInput): string {
  const used = hasShell ? uiPackages : [];
  return [
    `// GENERATED by \`pnpm scorpion profile:generate ${profileName}\`. Do not edit; regenerate instead.`,
    '// The web app learns the pages of the modules of its profile from this file only (ADR-0027).',
    "import type { UiModule } from '../lib/ui-modules.ts';",
    ...used.map((name, index) => `import * as ui${index} from '${name}/ui';`),
    '',
    `export const profileName = ${JSON.stringify(profileName)};`,
    '',
    '/** Whether the profile has `core.ui-shell`. Without it the image has no web app. */',
    `export const hasShell = ${hasShell};`,
    '',
    used.length > 0
      ? `export const uiModules: UiModule[] = [\n${used
          .map(
            (name, index) =>
              `  { package: ${JSON.stringify(name)}, routes: ui${index}.default, messages: ui${index}.messages },`,
          )
          .join('\n')}\n];`
      : 'export const uiModules: UiModule[] = [];',
    '',
  ].join('\n');
}
