import type { ModuleId } from './workspace-modules.ts';

/** A deployment profile: which modules an instance is built from. */
export interface Profile {
  readonly name: string;
  /** Module ids. A profile lists every module it needs, dependencies included. */
  readonly modules: readonly string[];
}

/**
 * Declares a profile. `modules` is checked against the modules in the workspace
 * (`WORKSPACE_MODULES`, generated by `pnpm modules:sync`), so a typo is a type error.
 */
export function defineProfile<const Modules extends readonly ModuleId[]>(profile: {
  name: string;
  modules: Modules;
}): Profile {
  return profile;
}
