// The generated chapter report and the README badge block (docs/implementation.md §8.2, §8.5).
import {
  ASVS_LEVEL,
  ASVS_VERSION,
  BADGE_END,
  BADGE_START,
  BEST_PRACTICES_ID,
  CHAPTERS,
  REPOSITORY,
  type ChapterConfig,
} from './config.ts';
import {
  blank,
  type Assessment,
  type DerivedStatus,
  type Entry,
  type Validation,
} from './assessment.ts';
import { assessed, type Chapter } from './source.ts';

const cell = (text: string): string => text.replace(/\s+/g, ' ').replace(/\|/g, '\\|').trim();

function evidenceLinks(entry: Entry): string {
  const items = (entry.evidence ?? []).map((item) => {
    if (item.test !== undefined) return `test \`[${item.test}]\``;
    const path = (item.code ?? item.doc)!;
    // The reports live in docs/security/asvs/, three levels below the repository root.
    return `${item.code !== undefined ? 'code' : 'doc'} [${cell(path)}](../../../${path})`;
  });
  return items.join('<br>');
}

function header(assessment: Assessment, config: ChapterConfig): string {
  const subject = `Self-assessment against OWASP ASVS ${ASVS_VERSION}, Level ${ASVS_LEVEL}, chapter ${config.chapter} ${config.name}`;
  const tail =
    'This is not a certification, and no independent party has reviewed it. OWASP does not certify projects.';
  if (
    blank(assessment.assessor) ||
    blank(assessment.assessed_commit) ||
    blank(assessment.assessed_on)
  ) {
    return `${subject}: not yet assessed by a person. The entries below are the working state, filled in with tests and code pointers; the maintainer's first pass and second pass are still to come. ${tail}`;
  }
  const second = blank(assessment.second_pass?.on)
    ? 'no second pass yet'
    : `second pass on ${assessment.second_pass!.on}`;
  return `${subject}, at commit \`${assessment.assessed_commit}\` on ${assessment.assessed_on}, ${second}. Assessor: ${assessment.assessor}. ${tail}`;
}

export function renderReport(
  assessment: Assessment,
  config: ChapterConfig,
  chapter: Chapter,
  validation: Validation,
  status: DerivedStatus,
): string {
  const byId = new Map(assessment.requirements.map((e) => [e.id, e]));
  const lines = [
    `# ASVS ${ASVS_VERSION} L${ASVS_LEVEL}: ${config.chapter} ${config.name}`,
    '',
    '<!-- Generated by `pnpm security:asvs --write` from the YAML file next to this one. Do not edit by hand. -->',
    '',
    `> ${header(assessment, config)}`,
    '',
    `Status: **${status}**. ${validation.counts.pass} pass, ${validation.counts['n/a']} n/a, ${validation.counts.fail} fail.`,
    '',
    '| Requirement | Level | Status | Evidence | Note |',
    '| --- | --- | --- | --- | --- |',
  ];
  for (const requirement of assessed(chapter)) {
    const entry = byId.get(requirement.id);
    const note =
      entry === undefined ? '' : entry.status === 'n/a' ? (entry.reason ?? '') : (entry.note ?? '');
    lines.push(
      `| **${requirement.number}** ${cell(requirement.text)} | L${requirement.level} | ${entry?.status ?? 'missing'} | ${entry ? evidenceLinks(entry) : ''} | ${cell(note)} |`,
    );
  }
  return `${lines.join('\n')}\n`;
}

const COLOURS: Record<DerivedStatus, string> = {
  'in progress': 'yellow',
  'self-assessed': 'brightgreen',
  'peer-reviewed': 'brightgreen',
  'externally verified': 'brightgreen',
  stale: 'lightgrey',
};

/** shields.io path text: `_` is a space and `--` a literal dash. */
const shield = (text: string): string => text.replace(/-/g, '--').replace(/ /g, '_');

export function renderBadgeBlock(statuses: ReadonlyMap<string, DerivedStatus>): string {
  const { org, repo } = REPOSITORY;
  // A blank line after the start marker, because Prettier puts one there in a Markdown file.
  const lines = [
    BADGE_START,
    '',
    `[![OpenSSF Best Practices](https://www.bestpractices.dev/projects/${BEST_PRACTICES_ID}/badge)](https://www.bestpractices.dev/projects/${BEST_PRACTICES_ID})`,
    `[![OpenSSF Scorecard](https://api.scorecard.dev/projects/github.com/${org}/${repo}/badge)](https://scorecard.dev/viewer/?uri=github.com/${org}/${repo})`,
  ];
  for (const config of CHAPTERS) {
    const status = statuses.get(config.chapter) ?? 'in progress';
    const label = `ASVS 5.0 L2 ${config.badgeName}`;
    lines.push(
      `[![${label}](https://img.shields.io/badge/${shield(label)}-${shield(status)}-${COLOURS[status]})](docs/security/asvs/${config.slug}.md)`,
    );
  }
  lines.push(BADGE_END);
  return lines.join('\n');
}

/** The README with the block between the markers replaced; undefined when the markers are missing or out of order. */
export function replaceBadgeBlock(readme: string, block: string): string | undefined {
  const start = readme.indexOf(BADGE_START);
  const end = readme.indexOf(BADGE_END);
  if (start === -1 || end === -1 || end < start) return undefined;
  return readme.slice(0, start) + block + readme.slice(end + BADGE_END.length);
}
